theme: minima
title: Grant Deane's Git Pages Site
author: Grant Deane
email: grantbdeane@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Grant Deane's personal web site. Hosted using Git Pages

# social links
github_username:  grantdeane

show_excerpts: true # set to false to remove excerpts on the homepage
